# Generated by Django 4.1.7 on 2023-02-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTable',
            fields=[
                ('booked_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_peoples', models.PositiveSmallIntegerField(default=1)),
                ('booking_time_x', models.DateTimeField()),
                ('booking_time_y', models.DateTimeField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('isCancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('measurement', models.CharField(max_length=40, null=True)),
                ('notice_if_below', models.PositiveIntegerField(default=10)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('update_remark', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isSpecial', models.TextField(default=None)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('order_item', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('P', 'Placed'), ('K', 'In Kitchen'), ('R', 'Ready'), ('D', 'Delivered')], default=('P', 'Placed'), max_length=100)),
                ('wait_time', models.TimeField()),
                ('isTakeaway', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('booked_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.bookedtable')),
                ('dish', models.ManyToManyField(to='fastrack_web.menu')),
                ('inventories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('map_link', models.TextField(null=True)),
                ('location', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_method', models.BooleanField(default=False)),
                ('credit_card_info', models.TextField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_seats', models.PositiveSmallIntegerField(default=1)),
                ('isVIP', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isBooked', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrack_web.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.user')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrack_web.restaurant'),
        ),
        migrations.AddField(
            model_name='bookedtable',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.restaurant'),
        ),
        migrations.AddField(
            model_name='bookedtable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.table'),
        ),
        migrations.AddField(
            model_name='bookedtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.user'),
        ),
    ]
