# Generated by Django 4.1.7 on 2023-03-07 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTable',
            fields=[
                ('booked_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_peoples', models.PositiveSmallIntegerField(default=1)),
                ('booking_time_x', models.DateTimeField()),
                ('booking_time_y', models.DateTimeField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('isCancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_method', models.BooleanField(default=False)),
                ('credit_card_info', models.TextField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('image_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('measurement', models.CharField(max_length=40, null=True)),
                ('notice_if_below', models.PositiveIntegerField(default=10)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('update_remark', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isSpecial', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.imagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('order_item', models.CharField(max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('order_status', models.CharField(choices=[('P', 'Placed'), ('K', 'In Kitchen'), ('R', 'Ready'), ('D', 'Delivered')], default=None, max_length=100, null=True)),
                ('wait_time', models.TimeField(null=True)),
                ('isTakeaway', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('booked_table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.bookedtable')),
                ('dish', models.ManyToManyField(to='fastrack_web.menu')),
                ('inventories', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('map_link', models.TextField(null=True)),
                ('location', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_seats', models.PositiveSmallIntegerField(default=1)),
                ('isVIP', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isBooked', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrack_web.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.customer')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.order')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrack_web.restaurant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrack_web.restaurant'),
        ),
        migrations.AddField(
            model_name='bookedtable',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.customer'),
        ),
        migrations.AddField(
            model_name='bookedtable',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.restaurant'),
        ),
        migrations.AddField(
            model_name='bookedtable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fastrack_web.table'),
        ),
    ]
