# Generated by Django 4.1.7 on 2023-02-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrack_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
    ]
