# Generated by Django 4.1.7 on 2023-02-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrack_web', '0002_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
