# Generated by Django 4.1.7 on 2023-02-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastrack_web', '0003_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='password',
        ),
    ]
